config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }
  root to: 'home#index'
  get '/dashboard', to: 'dashboard#index', as: 'dashboard'
  resources :projects
  get '/project/new', to: 'projects#create'
  get '/project/all', to: 'projects#index'
  get '/projects/:id/overview', to: 'projects#show'
  resources :invitations, only: [:index, :create, :destroy]
  resources :projects do
    resources :invitations, only: [:new, :create, :index, :destroy]
  end
  
  resources :invitations, only: [] do
    member do
      post 'accept'
      delete 'reject'
    end
  end

  resources :projects do
    resources :tasks
  end


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project
  belongs_to :assigned_user, class_name: 'User', foreign_key: 'user_id', optional: true
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    before_action :set_project
    before_action :set_task, only: [:show, :edit, :update, :destroy]
  
    def index
      @tasks = @project.tasks
      @project = Project.find(params[:project_id])
      @task = @project.tasks.build
      @users = User.all
      
    end
  
    def show
    end
  
    def new
      @task = @project.tasks.build
      @users = User.all
    end
  
    def create
        @project = Project.find(params[:project_id])
      @task = @project.tasks.build(task_params)
  
      if @task.save
        redirect_to project_tasks_path(@project), notice: 'Task was successfully created.'
      else
        render :new
      end
    end
  
    def edit
        @users = User.all
       @task = Task.find(params[:id])
    end
  
    def update
      if @task.update(task_params)
        redirect_to project_tasks_path(@project), notice: 'Task was successfully updated.'
      else
        render :edit
      end
    end
  
    def destroy
      @task.destroy
      redirect_to project_tasks_path(@project), notice: 'Task was successfully destroyed.'
    end
  
    private
  
    def set_project
      @project = Project.find(params[:project_id])
    end
  
    def set_task
      @task = @project.tasks.find(params[:id])
    end
  
    def task_params
      params.require(:task).permit(:name, :description, :due_date, :user_id, :priority)
    end
  end
  

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_edit_form.html.erb
<div>
    
            <!-- Edit Form -->
            <%= form_with(model: [ @project, task], local: true, id: "edit-form-#{task.id}") do |form| %>
              <% if task.errors.any? %>
                <div id="error_explanation">
                  <h2><%= pluralize(task.errors.count, 'error') %> prohibited this task from being saved:</h2>
                  <ul>
                    <% task.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                    <% end %>
                  </ul>
                </div>
              <% end %>
    
              <div class="field">
                <%= form.label :name %>
                <%= form.text_field :name %>
              </div>
    
              <div class="field">
                <%= form.label :description %>
                <%= form.text_area :description %>
              </div>
    
              <div class="field">
                <%= form.label :due_date %>
                <%= form.date_field :due_date %>
              </div>
    
              <div class="field">
                <%= form.label :user_id %>
                <%= form.collection_select :user_id, @users, :id, :email, prompt: true %>
              </div>
    
              <div class="field">
                <%= form.label :priority %>
                <%= form.select :priority, options_for_select([['High', 'high'], ['Medium', 'medium'], ['Low', 'low']]) %>
              </div>
    
              <div class="actions">
                <%= form.submit %>
              </div>
            <% end %>
          </div>

app/views/tasks/_form.html.erb
<%= form_with(model: [ @project, @task], local: true) do |form| %>
    <% if @task.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@task.errors.count, 'error') %> prohibited this task from being saved:</h2>
        <ul>
          <% @task.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>
  
    <div class="field">
      <%= form.label :description %>
      <%= form.text_area :description %>
    </div>
  
    <div class="field">
      <%= form.label :due_date %>
      <%= form.date_field :due_date %>
    </div>
  
    <div class="field">
      <%= form.label :user_id %>
      <%= form.collection_select :user_id, @users, :id, :email, prompt: true %>
    </div>

    <div class="field">
    <%= form.label :priority %>
    <%= form.select :priority, options_for_select([['High', 'high'], ['Medium', 'medium'], ['Low', 'low']]) %>
  </div>
  
    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
  

app/views/tasks/edit.html.erb
<!-- app/views/tasks/edit.html.erb -->
<h1>Edit Task</h1>

<%= form_with(model: [ @project, @task], local: true) do |form| %>
    <% if @task.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@task.errors.count, 'error') %> prohibited this task from being saved:</h2>
        <ul>
          <% @task.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>
  
    <div class="field">
      <%= form.label :description %>
      <%= form.text_area :description %>
    </div>
  
    <div class="field">
      <%= form.label :due_date %>
      <%= form.date_field :due_date %>
    </div>
  
    <div class="field">
      <%= form.label :user_id %>
      <%= form.collection_select :user_id, @users, :id, :email, prompt: true %>
    </div>

    <div class="field">
    <%= form.label :priority %>
    <%= form.select :priority, options_for_select([['High', 'high'], ['Medium', 'medium'], ['Low', 'low']]) %>
  </div>
  
    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
  

<%= link_to 'Show', project_task_path(@project, @task) %> |
<%= link_to 'Back', dashboard_path %>

app/views/tasks/new.html.erb
<!-- app/views/tasks/new.html.erb -->
<h1>New Task</h1>

<%= form_with(model: [ @project, @task], local: true) do |form| %>
    <% if @task.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@task.errors.count, 'error') %> prohibited this task from being saved:</h2>
        <ul>
          <% @task.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>
  
    <div class="field">
      <%= form.label :description %>
      <%= form.text_area :description %>
    </div>
  
    <div class="field">
      <%= form.label :due_date %>
      <%= form.date_field :due_date %>
    </div>
  
    <div class="field">
      <%= form.label :user_id %>
      <%= form.collection_select :user_id, @project.users, :id, :email, prompt: true %>
    </div>

    <div class="field">
    <%= form.label :priority %>
    <%= form.select :priority, options_for_select([['High', 'high'], ['Medium', 'medium'], ['Low', 'low']]) %>
  </div>
  
    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
  

app/views/tasks/show.html.erb
<!-- app/views/tasks/show.html.erb -->
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @task.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>

<p>
  <strong>Project:</strong>
  <%= @task.project.id %>
</p>

<p>
  <strong>User:</strong>
  <%= @task.user_id %>
</p>

<p>
  <strong>Due Date:</strong>
  <%= @task.due_date %>
</p>