config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }
  root to: 'home#index'
  get '/dashboard', to: 'dashboard#index', as: 'dashboard'
  resources :projects
  get '/project/new', to: 'projects#create'
  get '/project/all', to: 'projects#index'
  get '/projects/:id/overview', to: 'projects#show'
  resources :invitations, only: [:index, :create, :destroy]
  resources :projects do
    resources :invitations, only: [:new, :create, :index, :destroy]
  end
  
  resources :invitations, only: [] do
    member do
      post 'accept'
      delete 'reject'
    end
  end

  resources :projects do
    resources :tasks
  end


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :created_user, class_name: 'User'
  has_many :invitations
  has_and_belongs_to_many :users
  has_many :tasks, dependent: :destroy
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
    before_action :authenticate_user!
    
  def index
    @projects = current_user.projects
  end

  def new
    @project = current_user.projects.build
  end
  def show
    @project = Project.find(params[:id])
  @invitation = @project.invitations.build
  end

  def create
    @project = current_user.projects.build(project_params)

    if @project.save
      redirect_to dashboard_path, notice: 'Project was successfully created.'
    else
      render :new
    end
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])

    if @project.update(project_params)
      redirect_to project_path(@project), notice: 'Project was successfully updated.'
    else
      render :edit
    end
  end

  

  private

  def project_params
    params.require(:project).permit(:project_name, :description)
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<!-- app/views/projects/_form.html.erb -->

<%= form_with(model: project, url: project.persisted? ? project_path(project) : projects_path, method: project.persisted? ? :patch : :post, html: { class: "mb-3" }) do |form| %>
  <div class="mb-3">
    <%= form.label :project_name, class: "col-form-label" %>
    <%= form.text_field :project_name, class: "form-control", id: "project-name" %>
  </div>
  <div class="mb-3">
    <%= form.label :description, class: "col-form-label" %>
    <%= form.text_area :description, class: "form-control", id: "description" %>
  </div>
  <%= form.submit project.persisted? ? "Update Project" : "Create Project", class: "btn btn-primary" %>
<% end %>

app/views/projects/edit.html.erb
<!-- app/views/projects/edit.html.erb -->

<h1>Edit Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>Projects</h1>

<table>
  <thead>
    <tr>
      <th>Project Name</th>
    </tr>
  </thead>
  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.project_name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/projects/new.html.erb
# app/views/projects/new.html.erb

<h1>New Project</h1>

<%= form_with(model: @project, url: projects_path, method: :post) do |form| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% @project.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :project_name %>
    <%= form.text_field :project_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit "Create Project" %>
  </div>
<% end %>

<%= link_to 'Back', dashboard_path %>